/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './app.component';
import * as import2 from '@angular/common';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AppComponent,
  data: {}
}
);
function View_AppComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Hello Angular']))
  ]
  ,(null as any),(null as any));
}
function View_AppComponent_2(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    ))
  ]
  ,(null as any),(ck,v) => {
    const currVal_0:any = v.context.$implicit;
    ck(v,1,0,currVal_0);
  });
}
export function View_AppComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.AppComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.toggleHeading()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Toggle Heading'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_AppComponent_1)),
    import0.ɵdid(8192,(null as any),0,import2.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['List of Heroes'])),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_AppComponent_2)),
    import0.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import0.ViewContainerRef,
      import0.TemplateRef,
      import0.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any))
  ]
  ,(ck,v) => {
    var co:import1.AppComponent = v.component;
    const currVal_0:any = co.showHeading;
    ck(v,4,0,currVal_0);
    const currVal_1:any = co.heroes;
    ck(v,10,0,currVal_1);
  },(null as any));
}
function View_AppComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),(null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
    import0.ɵdid(24576,(null as any),0,import1.AppComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AppComponentNgFactory:import0.ComponentFactory<import1.AppComponent> = import0.ɵccf('my-app',import1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVGFtZXNoIFNpdmFndXJ1L1NvdXJjZSBDb2RlL0FuZ3VsYXIyQW9ULkV4YW1wbGUvQW5ndWxhcjJBb1QuRXhhbXBsZS9TY3JpcHRzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9UYW1lc2ggU2l2YWd1cnUvU291cmNlIENvZGUvQW5ndWxhcjJBb1QuRXhhbXBsZS9Bbmd1bGFyMkFvVC5FeGFtcGxlL1NjcmlwdHMvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvVGFtZXNoIFNpdmFndXJ1L1NvdXJjZSBDb2RlL0FuZ3VsYXIyQW9ULkV4YW1wbGUvQW5ndWxhcjJBb1QuRXhhbXBsZS9TY3JpcHRzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvVGFtZXNoIFNpdmFndXJ1L1NvdXJjZSBDb2RlL0FuZ3VsYXIyQW9ULkV4YW1wbGUvQW5ndWxhcjJBb1QuRXhhbXBsZS9TY3JpcHRzL3NyYy9hcHAvYXBwLmNvbXBvbmVudC50cy5BcHBDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCI8YnV0dG9uIChjbGljayk9XCJ0b2dnbGVIZWFkaW5nKClcIj5Ub2dnbGUgSGVhZGluZzwvYnV0dG9uPlxyXG48aDEgKm5nSWY9XCJzaG93SGVhZGluZ1wiPkhlbGxvIEFuZ3VsYXI8L2gxPlxyXG5cclxuPGgzPkxpc3Qgb2YgSGVyb2VzPC9oMz5cclxuPGRpdiAqbmdGb3I9XCJsZXQgaGVybyBvZiBoZXJvZXNcIj57e2hlcm99fTwvZGl2PiIsIjxteS1hcHA+PC9teS1hcHA+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNDQTtJQUF3Qjs7Ozs7O0lBR3hCO0lBQWlDO01BQUE7TUFBQTtJQUFBO0lBQUE7OztJQUFBO0lBQUE7Ozs7O01BSmpDO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQVE7UUFBQTtRQUFBO01BQUE7TUFBUjtJQUFBO0lBQWtDO0lBQXVCO0lBQ3pEO2dCQUFBOzs7SUFBQTtPQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBMEM7SUFFMUM7SUFBSTtJQUFtQjtJQUN2QjtnQkFBQTs7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTs7OztJQUhJO0lBQUosU0FBSSxTQUFKO0lBR0s7SUFBTCxVQUFLLFNBQUw7Ozs7O0lDSkE7Z0JBQUE7Ozs7In0=
